# Generated by Django 4.1 on 2022-09-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nazwa")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1024, null=True, verbose_name="Opis"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data rozpoczęcia"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data zakńczenia"
                    ),
                ),
                (
                    "specialist_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ilość specialistów"
                    ),
                ),
                (
                    "market_branch",
                    models.TextField(blank=True, verbose_name="Gałąź rynku"),
                ),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekty",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nazwa"),
                ),
            ],
            options={
                "verbose_name": "Narzędzie",
                "verbose_name_plural": "Narzędzia",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=1024)),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_tasks",
                        related_query_name="sub_task",
                        to="project.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zadanie",
                "verbose_name_plural": "Zadania",
                "ordering": ["-id"],
            },
        ),
    ]
