# Generated by Django 4.1 on 2022-10-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_remove_tools"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tool",
        ),
    ]
