# Generated by Django 4.1 on 2022-09-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Data zakończenia"
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                to="generator.technology",
                verbose_name="Dodatkowe umiejętności",
            ),
        ),
    ]
