# Generated by Django 4.1 on 2022-10-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0002_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialist",
            name="tools",
        ),
        migrations.RemoveField(
            model_name="specialistproject",
            name="tools",
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Nazwa"),
        ),
        migrations.AlterField(
            model_name="technology",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Nazwa"),
        ),
    ]
