# Generated by Django 4.1 on 2023-01-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_remove_tools"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialistproject",
            options={
                "ordering": ["-display_priority"],
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekty",
            },
        ),
        migrations.AddField(
            model_name="specialistproject",
            name="display_priority",
            field=models.FloatField(default=0, verbose_name="Priorytet wyświetlania"),
        ),
    ]
